FROM debian as builder

RUN apt-get -y -qq update  && \
    apt-get -y -qq upgrade  && \
    apt-get -y -qq install make \
            g++ \
            m4 \
            cmake \
            clang \
            libclang-dev \
            openssl \
            zlib1g-dev \
            llvm \
            llvm-dev \
            xutils-dev \
            autoconf \
            autoconf-archive \
            automake \
            libc-dev \
            linux-libc-dev \
            build-essential \
            pkgconf \
            curl

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /usr/src/purplecoin

COPY . .
RUN cargo +nightly build --release --no-default-features --features "rpc wallet disk miner blake3sum"

FROM debian

ENV RUST_LOG=purplecoin

# Network settings
ENV PURPLECOIN_NETWORK_LISTENADDR=
ENV PURPLECOIN_NETWORK_LISTENPORTMAINNET=8098
ENV PURPLECOIN_NETWORK_LISTENPORTTESTNET=8032
ENV PURPLECOIN_NETWORK_RPCENABLED=
ENV PURPLECOIN_NETWORK_RPCLISTENPORTMAINNET=8067
ENV PURPLECOIN_NETWORK_RPCLISTENPORTTESTNET=8037
ENV PURPLECOIN_NETWORK_RPCUSERNAME=
ENV PURPLECOIN_NETWORK_RPCPASSWORD=
ENV PURPLECOIN_NETWORK_SEEDSMAINNET=
ENV PURPLECOIN_NETWORK_SEEDSTESTNET=
ENV PURPLECOIN_NETWORK_ISBOOTSTRAPNODE=false
ENV PURPLECOIN_NETWORK_BOOTSTRAPNODEPEERID=12D3KooWDGzJy3Qh2d28ygPo4ghQSTkhewLRDtr7gByANXV2cAFU
ENV PURPLECOIN_NETWORK_BOOTSTRAPNODEADDRESS=/ip4/172.22.0.2/tcp/8031

# Node settings
ENV PURPLECOIN_NODE_NETWORKNAME=
ENV PURPLECOIN_NODE_VERIFIERTHREADS=
ENV PURPLECOIN_NODE_NETWORKTHREADS=
ENV PURPLECOIN_NODE_RANDOMXFASTMODE=
ENV PURPLECOIN_NODE_ARCHIVALMODE=
ENV PURPLECOIN_NODE_PRUNEHEADERS=
ENV PURPLECOIN_NODE_PRUNETRANSACTIONS=
ENV PURPLECOIN_NODE_PRUNEUTXOS=
ENV PURPLECOIN_NODE_DATADIR=
ENV PURPLECOIN_NODE_MEMORYONLY=
ENV PURPLECOIN_NODE_MEMPOOLSIZE=
ENV PURPLECOIN_NODE_DHTBRIDGEENABLED=
ENV PURPLECOIN_NODE_DHTBRIDGESTORAGEMB=
ENV PURPLECOIN_NODE_SAVEUTXOADDRESSES=
ENV PURPLECOIN_NODE_SAVEUTXOASSETS=
ENV PURPLECOIN_NODE_BRIDGEPUBLICQUERIES=
ENV PURPLECOIN_NODE_BRIDGEHTTPQUERIES=
ENV PURPLECOIN_NODE_BRIDGEHTTPLISTENPORT=8080
ENV PURPLECOIN_NODE_BRIDGEHTTPHMACKEY=

# Miner settings
ENV PURPLECOIN_MINER_ONLYSECTORS=
ENV PURPLECOIN_MINER_ONLYALGOS=
ENV PURPLECOIN_MINER_COINBASEADDRESS=
ENV PURPLECOIN_MINER_MINERTHREADS=

# Cluster settings
ENV PURPLECOIN_CLUSTER_CLUSTERENABLED=
ENV PURPLECOIN_CLUSTER_CLUSTERDISCOVERYPORT=3034
ENV PURPLECOIN_CLUSTER_CLUSTERDISCOVERYLISTENADDR=
ENV PURPLECOIN_CLUSTER_CLUSTERCOOKIE=
ENV PURPLECOIN_CLUSTER_VNODESPERSHARD=
ENV PURPLECOIN_CLUSTER_VNODESREPLICATIONFACTOR=
ENV PURPLECOIN_CLUSTER_BLOCKWRITES=
ENV PURPLECOIN_CLUSTER_REPLICATIONMODE=
ENV PURPLECOIN_CLUSTER_REPLICATIONDATACENTER=
ENV PURPLECOIN_CLUSTER_CLUSTERIPS=

# Expose ports
EXPOSE $PURPLECOIN_NETWORK_LISTENPORTMAINNET/tcp
EXPOSE $PURPLECOIN_NETWORK_LISTENPORTMAINNET/udp
EXPOSE $PURPLECOIN_NETWORK_RPCLISTENPORTMAINNET/tcp
EXPOSE $PURPLECOIN_NETWORK_RPCLISTENPORTMAINNET/udp
EXPOSE $PURPLECOIN_NETWORK_LISTENPORTTESTNET/tcp
EXPOSE $PURPLECOIN_NETWORK_LISTENPORTTESTNET/udp
EXPOSE $PURPLECOIN_NETWORK_RPCLISTENPORTTESTNET/tcp
EXPOSE $PURPLECOIN_NETWORK_RPCLISTENPORTTESTNET/udp
EXPOSE $PURPLECOIN_NODE_BRIDGEHTTPLISTENPORT/tcp
EXPOSE $PURPLECOIN_NODE_BRIDGEHTTPLISTENPORT/udp
EXPOSE $PURPLECOIN_CLUSTER_CLUSTERDISCOVERYPORT/tcp
EXPOSE $PURPLECOIN_CLUSTER_CLUSTERDISCOVERYPORT/udp

COPY --from=builder /usr/src/purplecoin/target/release/purplecoin /purplecoin

ENTRYPOINT ["/purplecoin"]
