[toolchain]
channel = "nightly"
components = [ "rustfmt", "clippy", "rust-docs" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-apple-darwin", "aarch64-unknown-linux-musl" ]